[workspace]
name = "MILP"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
python = "3.11.*"
ecole = "*"
pytorch = "*"
numpy = "*"
jupyter = "*"
tqdm = "*"
pip = "*"

[pypi-dependencies]
torch-geometric = "*"
